# Generated by Django 4.2.27 on 2025-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITAAudioStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='aita/')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EssayAudioStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('essay_id', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='essay/')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
