# Generated by Django 6.0.3 on 2026-04-05 22:14

import audio_capture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('trial_id', models.IntegerField()),
                ('audio_file', models.FileField(upload_to=audio_capture.models.audio_path)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
