# Generated by Django 5.2 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_name', models.CharField(max_length=50)),
                ('question_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('expired', 'Expired')], default='assigned', max_length=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='questionassignment',
            index=models.Index(fields=['trial_name', 'question_id', 'status'], name='audio_captu_trial_n_a88872_idx'),
        ),
        migrations.AddIndex(
            model_name='questionassignment',
            index=models.Index(fields=['user_id', 'status'], name='audio_captu_user_id_fe872f_idx'),
        ),
    ]
