# Generated by Django 4.2.27 on 2026-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaaudiostorage',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
