# Generated by Django 6.0.2 on 2026-02-10 15:20

import audio_capture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_capture', '0002_aitaaudiostorage_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitaaudiostorage',
            name='audio_file',
            field=models.FileField(upload_to=audio_capture.models.aita_audio_path),
        ),
        migrations.AlterField(
            model_name='essayaudiostorage',
            name='audio_file',
            field=models.FileField(upload_to=audio_capture.models.essay_audio_path),
        ),
    ]
