# Generated by Django 6.0.3 on 2026-09-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_capture', '0002_questionassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionassignment',
            name='trial_name',
            field=models.CharField(max_length=100),
        ),
    ]
